### ISSUE TITLE
Do we need Developer Mode enabled to execute tests?

### ISSUE THREAD

**Issue by johnpatrickdev** [licanhua/YWinAppDriver#32]
Hi,

One of the core concern in adopting WinAppDriver is a pre-requisite on Enabling Developer mode.

1. With YWinAppDriver, do we still need to enable Developer Mode?
2. How easy to migrate frameworks and Test Scripts from WinAppDriver to YWinAppDriver?

Thanks,
John

**Comment by licanhua** [comment]
For your first question, It depends on what kind of app you are testing. If you are test app is UWP, likely yes because you have to enable developer mode to install the test app. I don't think YWinAppDriver requires you do this （of course I may have wrong statement here because I always have developer mode enabled in my machine)
It's hard to tell how easy. If you are using a feature YWinAppDriver doesn't have but WinAppDriver have, then it's hard because you have to modify YWinAppDriver and fix it by yourself. If you are just have clicking event, very likely it's an easy task.
